### PR TITLE
Add a simple (and barely functional) UI

### PR DESCRIPTION
**Pull request by chriskd**
Allows you to specify the package name to dump and the output directory without having to rebuild the package every time. A reboot is required after setting the values.

### CODE REVIEW

**Comment by CunningLogic** [comment]
Chris,

Soon as I Can compile and test I will merge, can't do it right now (had my eyes zapped). I appreciate it. Can you tell me what devices you tested it on, by change anything 5.x? or anything running ART?

JC

**Comment by chriskd** [comment]
Awesome, no rush. I tested it on a Nexus 4 running 4.4.4, haven't tested it
on anything 5.x+ yet. I wasn't able to get the changes to take effect
without a reboot, but I suspect that may have to do with how Xposed loads
the module (haven't used Xposed much before). It's super basic, but seems
to work alright.

Good luck with the recovery! I'm not a fan of my glasses, but I'm also not
a fan of having lasers anywhere near my eyes.

**Comment by chriskd** [comment]
BTW, my initial commit had some issues. Just pushed the fixes.

**Comment by CunningLogic** [comment]
chriskd,

Do you mind incrementing the versioncode and version number to 1.2 and I'll merge. I will probably abandon DexHook after this merge, in favor of a newer module I am working on.

**Comment by chriskd** [comment]
Done. Lemme know if I can do anything else. I'll keep an eye out for this new module; also down to help with that if needed :)

**Pull request merged**
